tasks:
  build-image:
    steps:
    - checkout
    - docker/build:
        image: demo/todomvc

  gem-install:
    steps:
    - checkout
    - commands:
      - gem install bundler -v 1.16.1
      - bundle check || bundle install --without test development
